[package]
name = "geometry"
version = "0.1.0"
authors = ["luhem7 <mehul.gang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random_color = "0.4.4"
